### PR TITLE
Scheduluer CLI: Added optional logging config

### PR DESCRIPTION
**Pull request by MuriloScarpaSitonio**
Similar to #159.

### CODE REVIEW

**Review by s3rius — APPROVED** [review]
Thank you very much for noticing. It's really helpful. But please fix some styling issues before merging.

**Comment by MuriloScarpaSitonio** [comment]
@s3rius I think I fixed. Thanks!

**Review by s3rius — APPROVED** [review]
Seems good. Thanks.

**Comment by s3rius** [comment]
You can fix almost all issues automatically by running `pre-commit run -a`.

**Comment by MuriloScarpaSitonio** [comment]
I ran `poetry run pre-commit` before and now `pre-commit run -a`: it changed the formatting back and forth...

**Comment by MuriloScarpaSitonio** [comment]
Hey @s3rius, not trying to rush or anything but do you have an estimate when this will be merged to master?

**Comment by s3rius** [comment]
@MuriloScarpaSitonio, you won't believe me. But it's released.

**Comment by s3rius** [comment]
image

**Comment by MuriloScarpaSitonio** [comment]
@s3rius you da man!

**Pull request merged**
