### PR TITLE
Separation of the receiver from the CLI

### PR DESCRIPTION
**Pull request by hugiron**

### CODE REVIEW

**Review by s3rius — CHANGES_REQUESTED** [review]
Since you've moved the `async_listen_messages` function inside of the receiver, you need to delete original `async_listen_messages` function. Because we don't want to have deadcode in our codebase, right?

**Comment by hugiron** [comment]
@s3rius already

**Review by s3rius — APPROVED** [review]
Ah, I see. My bad. Yeah, it's good.

**Comment by s3rius** [comment]
But change brach to develop.

**Pull request merged**
