### PR TITLE
feat: set/get progress of task execution

### PR DESCRIPTION
**Pull request by Sobes76rus**
Hello there! I would like to add some methods to set/get progress of tasks executions
In Celery u can do it with `update_state`

### CODE REVIEW

**Comment by s3rius** [comment]
Hi and thanks for creating this PR. I have a question regarding API for setting a progress from within a task. How's it going to be implemented?

**Comment by s3rius** [comment]
I guess, we can introduce new dependency for base context, that can work with progresses.

**Comment by Sobes76rus** [comment]
I can use `context.broker.result_backend.set_progress`
Or provide some addition function to dependencies for it

**Comment by s3rius** [comment]
@Sobes76rus, I guess it's better to have a class-based dependency with tab-completed methods.

```python
from taskiq import Context

class TaskState(enum.Enum):
	PENDING = enum.auto()
	STARTED = enum.auto()
	...


class ProgressTracker:
	def __init__(self, context: Context = Depends()):
		self.context = context
	
	def set_progress(self,  state: TaskState, meta: Dict[str, Any]) -> None:
		...

```

**Comment by Sobes76rus** [comment]
Ok, ill do it

**Pull request closed without merging**
